name: 'AutomagicallyExecutor'
description: 'Trigger Automagically given a url and a valid token'
inputs:
  url: 
    description: 'Url of the app to test'
    required: true
  token:
    description: 'Your unique identifier'
    required: true
  testTargetId:
    description: 'Your test target id'
    required: true
  automagicallyBaseUrl:
    description: 'Base URL of the automagically instance, for switching between production and staging. Defaults to Production url'
    required: false
  blocking:
    description: 'If the pipeline should be blocked until all test results in the test report are passed'
    required: false
outputs:
  testReportUrl:
    description: 'Url to resulting test report'
runs:
  using: 'node22'
  main: 'dist/index.js'

branding:
  icon: check-circle
  color: purple
