name: 'AutomagicallyExecutor'
description: 'Trigger Automagically given a url and a valid token'
inputs:
  url: 
    description: 'Url of the app to test'
    required: true
  token:
    description: 'Your unique identifier'
    required: true
  testTargetId:
    description: 'Your test target id'
    required: true
  automagicallyBaseUrl:
    description: 'Base URL of the automagically instance, for switching between production and staging. Defaults to Production url'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
